In [31]:
# Lers start with grid search
from sklearn import datasets, svm
import pandas as pd
iris = datasets.load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [15]:
dir(iris)

['DESCR',
 'data',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [23]:
df = pd.DataFrame(iris.data, columns = iris.feature_names)
df['flower'] = iris.target
df.flower

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: flower, Length: 150, dtype: int32

In [27]:
# copying the vlues into flower columsn
df['flower'] = df['flower'].apply(lambda x: iris.target_names[x])

df[47:52]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
47                4.6               3.2                1.4               0.2   
48                5.3               3.7                1.5               0.2   
49                5.0               3.3                1.4               0.2   
50                7.0               3.2                4.7               1.4   
51                6.4               3.2                4.5               1.5   

    flower  
47  setosa  
48  setosa  
49  setosa  
50  setosa  
51  setosa

In [53]:
# Lets train this data sets/
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size = 0.2)

In [54]:
model = svm.SVC(kernel = 'linear', C = 40, gamma = 'auto')#by kernel = 'linear', gamma = 'scale ' the accuracy increases to 93 percent
model.fit(x_train, y_train)
model.score(x_test, y_test)

0.9666666666666667

In [111]:
from sklearn.model_selection import cross_val_score
import numpy as np

In [66]:
# applying the cvc on svm model
cross_val_score(svm.SVC(kernel = 'linear', C = 40, gamma = 'scale'), iris.data, iris.target, cv =5) # cv is cross validation
# max score of svm

array([1. , 1. , 0.9, 0.9, 1. ])

In [67]:
cross_val_score(svm.SVC(kernel = 'rbf', C = 40, gamma = 'scale'), iris.data, iris.target, cv =5)

array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [68]:
cross_val_score(svm.SVC(kernel = 'linear', C = 80, gamma = 'auto'), iris.data, iris.target, cv =5)

array([1.        , 1.        , 0.9       , 0.93333333, 1.        ])

#### instead of checking all the possible parameters we can use for loop to get random values

In [75]:
kernels = ['rbf', 'linear']
C = [10, 40, 100]
avg_score = {}
for kval in kernels:
    for cval in C:
        cv_score  = cross_val_score(svm.SVC(kernel = kval, C =cval, gamma = 'auto'), iris.data, iris.target, cv =5)
        avg_score[kval  +'_' + str(cval)] = np.average(cv_score)
        
avg_score

{'rbf_10': 0.9800000000000001,
 'rbf_40': 0.96,
 'rbf_100': 0.96,
 'linear_10': 0.9733333333333334,
 'linear_40': 0.96,
 'linear_100': 0.9666666666666666}

In [ ]:
# We have a model called GridsearchCV that do exact same like above loop

In [79]:
from sklearn.model_selection import GridSearchCV
clf = GridSearchCV(svm.SVC(gamma = 'auto'),  {
    'C' : [10, 20, 50],
    'kernel': ['linear', 'rbf'] 
},cv = 5, return_train_score = False)



In [80]:
# lets make some fitting
clf.fit(iris.data, iris.target)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [10, 20, 50], 'kernel': ['linear', 'rbf']})

In [81]:
clf.cv_results_

{'mean_fit_time': array([0.00154338, 0.00120959, 0.00179219, 0.00090914, 0.        ,
        0.00019779]),
 'std_fit_time': array([0.00079703, 0.00088339, 0.00358438, 0.00121238, 0.        ,
        0.00039558]),
 'mean_score_time': array([0.00110159, 0.00080051, 0.        , 0.00040512, 0.        ,
        0.        ]),
 'std_score_time': array([0.00017851, 0.00067531, 0.        , 0.00049625, 0.        ,
        0.        ]),
 'param_C': masked_array(data=[10, 10, 20, 20, 50, 50],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['linear', 'rbf', 'linear', 'rbf', 'linear', 'rbf'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 10, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 50, 'kernel': 'linear'},
  {'C': 50, 'kernel': 'rbf'

In [84]:
# cv_results_ are bit ambiguous
# lets take them into dataframe
df = pd.DataFrame(clf.cv_results_)
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.001543      0.000797         0.001102        0.000179      10   
1       0.001210      0.000883         0.000801        0.000675      10   
2       0.001792      0.003584         0.000000        0.000000      20   
3       0.000909      0.001212         0.000405        0.000496      20   
4       0.000000      0.000000         0.000000        0.000000      50   
5       0.000198      0.000396         0.000000        0.000000      50   

  param_kernel                         params  split0_test_score  \
0       linear  {'C': 10, 'kernel': 'linear'}           1.000000   
1          rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
2       linear  {'C': 20, 'kernel': 'linear'}           1.000000   
3          rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   
4       linear  {'C': 50, 'kernel': 'linear'}           1.000000   
5          rbf     {'C': 50, 'kernel': 'rbf'}           1.000000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           1.000000           0.900000           0.966667                1.0   
1           1.000000           0.966667           0.966667                1.0   
2           1.000000           0.900000           0.933333                1.0   
3           1.000000           0.900000           0.966667                1.0   
4           1.000000           0.900000           0.933333                1.0   
5           0.966667           0.900000           0.933333                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.973333        0.038873                2  
1         0.980000        0.016330                1  
2         0.966667        0.042164                4  
3         0.966667        0.036515                3  
4         0.966667        0.042164                4  
5         0.960000        0.038873                6

In [85]:
# getting out some good factors for outputs
df[['param_C', 'param_kernel', 'mean_test_score']]

param_C param_kernel  mean_test_score
0      10       linear         0.973333
1      10          rbf         0.980000
2      20       linear         0.966667
3      20          rbf         0.966667
4      50       linear         0.966667
5      50          rbf         0.960000

In [86]:
clf.best_score_

0.9800000000000001

In [88]:
clf.best_params_

{'C': 10, 'kernel': 'rbf'}

In [ ]:
# if we apply C(combinatiion and permutation value from 1 --> 150 then it will cost alot by computation)
# there comes sklearn library randomized search CV


In [91]:
from sklearn.model_selection import RandomizedSearchCV
rsv = RandomizedSearchCV(svm.SVC(gamma = 'auto'),  {
    'C' : [10, 20, 50],
    'kernel': ['linear', 'rbf'] 
},cv = 5, return_train_score = False, n_iter = 2) # n_iter means try only 2 combinations



In [93]:
rsv.fit(iris.data, iris.target)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=2,
                   param_distributions={'C': [10, 20, 50],
                                        'kernel': ['linear', 'rbf']})

In [94]:
# downlod the result into data frame
pd.DataFrame(rsv.cv_results_)[['param_C', 'param_kernel', 'mean_test_score']]

param_C param_kernel  mean_test_score
0      20       linear         0.966667
1      10       linear         0.973333

In [95]:
# lets try different models to learn what are expected scores
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [101]:
# Lets save some params for different models to get some scores

model_params = {
    
    'svm':{
        'model':svm.SVC(gamma = 'auto'),
        'params': {
            'C': [1, 20, 50],
            'kernel': ['rbf', 'linear']
            }
    },
    
    'random_forest':{
        'model':RandomForestClassifier(),
        'params': {
            'n_estimators': [1, 20, 50]
            }
    },
    
    'logistic_regression':{
        'model':LogisticRegression(solver = 'liblinear', multi_class = 'auto'),
        'params': {
            'C': [1, 20, 50]
            }
    },
}

In [97]:
# Storing scores
score = []
for model_name, mp in model_params.items():
    clf = GridSearchCV(mp['model'], mp['params'], cv = 5, return_train_score = False)
    clf.fit(iris.data, iris.target)
    score.append(
    {
        'model': model_name,
        'best_score': clf.best_score_,
        'best_params': clf.best_params_
    })
    

In [102]:
# Convert this score into data frame
df = pd.DataFrame(score, columns = ['model','best_score', 'best_params'])
df

model  best_score                best_params
0                  svm    0.980000  {'C': 1, 'kernel': 'rbf'}
1        random_forest    0.960000       {'n_estimators': 50}
2  logistic_regression    0.973333                  {'C': 50}

## Excercise 

In [107]:
from sklearn.datasets import load_digits
digits = load_digits()
digits.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [109]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size = 0.2)

In [110]:
model = svm.SVC(kernel = 'linear', C = 40, gamma = 'auto')#by kernel = 'linear', gamma = 'scale ' the accuracy increases to 93 percent
model.fit(x_train, y_train)
model.score(x_test, y_test)

0.9777777777777777

In [112]:
# using cross values functions
from sklearn.model_selection import cross_val_score
import numpy as np

In [113]:
kernels = ['rbf', 'linear']
C = [10, 40, 100]
avg_score = {}
for kval in kernels:
    for cval in C:
        cv_score  = cross_val_score(svm.SVC(kernel = kval, C =cval, gamma = 'auto'), digits.data, digits.target, cv =5)
        avg_score[kval  +'_' + str(cval)] = np.average(cv_score)
        
avg_score

{'rbf_10': 0.47636645001547506,
 'rbf_40': 0.47636645001547506,
 'rbf_100': 0.47636645001547506,
 'linear_10': 0.9476973073351903,
 'linear_40': 0.9476973073351903,
 'linear_100': 0.9476973073351903}

In [114]:
# doing by grid search cv
from sklearn.model_selection import GridSearchCV
clf = GridSearchCV(svm.SVC(gamma = 'auto'),  {
    'C' : [10, 20, 50],
    'kernel': ['linear', 'rbf'] 
},cv = 5, return_train_score = False)


In [116]:
# data training by gridsearch
clf.fit(digits.data, digits.target)
clf.cv_results_

{'mean_fit_time': array([0.06806417, 0.77521334, 0.06950984, 0.79483433, 0.06909585,
        0.87948241]),
 'std_fit_time': array([0.00453178, 0.03023606, 0.00469504, 0.04871808, 0.0057889 ,
        0.16242606]),
 'mean_score_time': array([0.01876559, 0.09037981, 0.01807442, 0.09231763, 0.01870422,
        0.09042406]),
 'std_score_time': array([0.00148166, 0.00542206, 0.00195331, 0.00577988, 0.00176605,
        0.00422299]),
 'param_C': masked_array(data=[10, 10, 20, 20, 50, 50],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['linear', 'rbf', 'linear', 'rbf', 'linear', 'rbf'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 10, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 50, 'kernel': 'linear'},
  {'C': 50, 'kernel': 'rbf'

In [117]:
# cv_results_ are bit ambiguous
# lets take them into dataframe
df = pd.DataFrame(clf.cv_results_)
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.068064      0.004532         0.018766        0.001482      10   
1       0.775213      0.030236         0.090380        0.005422      10   
2       0.069510      0.004695         0.018074        0.001953      20   
3       0.794834      0.048718         0.092318        0.005780      20   
4       0.069096      0.005789         0.018704        0.001766      50   
5       0.879482      0.162426         0.090424        0.004223      50   

  param_kernel                         params  split0_test_score  \
0       linear  {'C': 10, 'kernel': 'linear'}           0.963889   
1          rbf     {'C': 10, 'kernel': 'rbf'}           0.452778   
2       linear  {'C': 20, 'kernel': 'linear'}           0.963889   
3          rbf     {'C': 20, 'kernel': 'rbf'}           0.452778   
4       linear  {'C': 50, 'kernel': 'linear'}           0.963889   
5          rbf     {'C': 50, 'kernel': 'rbf'}           0.452778   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           0.919444           0.966574           0.963788           0.924791   
1           0.469444           0.479109           0.479109           0.501393   
2           0.919444           0.966574           0.963788           0.924791   
3           0.469444           0.479109           0.479109           0.501393   
4           0.919444           0.966574           0.963788           0.924791   
5           0.469444           0.479109           0.479109           0.501393   

   mean_test_score  std_test_score  rank_test_score  
0         0.947697        0.020978                1  
1         0.476366        0.015784                4  
2         0.947697        0.020978                1  
3         0.476366        0.015784                4  
4         0.947697        0.020978                1  
5         0.476366        0.015784                4

In [118]:
df[['param_C', 'param_kernel', 'mean_test_score']]

param_C param_kernel  mean_test_score
0      10       linear         0.947697
1      10          rbf         0.476366
2      20       linear         0.947697
3      20          rbf         0.476366
4      50       linear         0.947697
5      50          rbf         0.476366

In [119]:
clf.best_score_

0.9476973073351903

In [121]:
# lets try different models to learn what are expected scores
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier



In [135]:
model_params = {
    
    'svm':{
        'model':svm.SVC(gamma = 'auto'),
        'params': {
            'C': [1, 20, 50],
            'kernel': ['rbf', 'linear']
            }
    },
    
    'random_forest':{
        'model':RandomForestClassifier(),
        'params': {
            'n_estimators': [1, 20, 50]
            }
    },
    
    'logistic_regression':{
        'model':LogisticRegression(solver = 'liblinear', multi_class = 'auto'),
        'params': {
            'C': [1, 20, 50]
            }
    },
    
    'GaussianNB ':{
        'model':GaussianNB(),
        'params': {
#             'C': [1, 20, 50]
            }
    },
    
    'MultinomialNB ':{
        'model':MultinomialNB(),
        'params': {
#             'C': [1, 20, 50]
            }
    },
    
     
    'decision_tree ':{
        'model':DecisionTreeClassifier(),
        'params': {
            'criterion': ['gini','entropy']
        
            }
    },

}

In [136]:
score = []
for model_name, mp in model_params.items():
    clf = GridSearchCV(mp['model'], mp['params'], cv = 5, return_train_score = False)
    clf.fit(digits.data, digits.target)
    score.append(
    {
        'model': model_name,
        'best_score': clf.best_score_,
        'best_params': clf.best_params_
    })

In [138]:
# Convert this score into data frame
df = pd.DataFrame(score, columns = ['model','best_score', 'best_params'])
df

model  best_score                   best_params
0                  svm    0.947697  {'C': 1, 'kernel': 'linear'}
1        random_forest    0.937137          {'n_estimators': 50}
2  logistic_regression    0.922114                      {'C': 1}
3          GaussianNB     0.806928                            {}
4       MultinomialNB     0.870350                            {}
5       decision_tree     0.802457      {'criterion': 'entropy'}